replicaCount: 1

image:
  repository: jellyfin/jellyfin
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8096

ingress:
  enabled: true
  hosts: []
  #- host: jellyfin.example.com
  #  tls:
  #    enabled: true
  #    name: tls-secret
  #    cert: base64EncodedCertificate
  #    key: base64EncodedKey

storage:
  className: jellyfin-storage
  basePath: /nas/plex
  hostname: cronos
  sizes:
    # You need to define the local directories like /basepath/config, /basepath/cache, /basepath/media...
    # On the container side we will have /config, /cache, /media... with sizes defined
    config: 5Gi
    cache: 10Gi
    peliculas: 1500Gi
    series: 500Gi