replicaCount: 1

image:
  repository: jellyfin/jellyfin
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8096

ingress:
  enabled: true
  host: jellyfin.luisva.com
  tls:
    name: tls-secret
    cert: base64EncodedCertificate
    key: base64EncodedKey

storage:
  className: local-storage
  basePath: /basepath 
  hostname: cronos
  sizes:
    # You need to define the local directories like /basepath/config, /basepath/cache, /basepath/media...
    # On the container side we will have /config, /cache, /media... with sizes defined
    config: 5Gi
    cache: 10Gi
    media: 100Gi